on:
  workflow_dispatch:
  repository_dispatch:
    types: [release_event]

name: Transform Data

permissions:
  contents: read
  # Lets download-artifact use the REST API rather than the internal artifact
  # service, which intermittently 404s on runs with several re-run attempts.
  actions: read

jobs:
  # ------------------------------------------------------------------------------
  # Download retrieved data once and share via artifact
  # ------------------------------------------------------------------------------
  download_retrieved_data:
    name: Download Retrieved Data
    runs-on: ubuntu-latest
    steps:
      - uses: clusterflick/release-downloader@v3
        with:
          token: ${{ secrets.PAT }}
          repository: "clusterflick/data-retrieved"
          latest: true
          fileName: "*"
          out-file-path: "retrieved-data"
      - name: Upload Retrieved Data
        uses: actions/upload-artifact@v7
        with:
          name: retrieved-data
          path: retrieved-data/
          retention-days: 1

  # ------------------------------------------------------------------------------
  # Download historical combined data (last 10 days) and share via artifact
  # ------------------------------------------------------------------------------
  download_historical_data:
    name: Download Historical Data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
          repository: clusterflick/scripts
      - name: Download Last 10 Days Combined Data
        run: bash helpers/get-last-10-days-combined-data.sh
      - name: Upload Historical Data
        uses: actions/upload-artifact@v7
        with:
          name: combined-data
          path: combined-data/
          retention-days: 1

  # ------------------------------------------------------------------------------
  # Transform BFI
  # ------------------------------------------------------------------------------
  transform_bfi:
    name: Transform BFI
    needs: [download_retrieved_data, download_historical_data]
    runs-on: ubuntu-latest
    env:
      TZ: Europe/London
      MOVIEDB_API_KEY: ${{ secrets.MOVIEDB_API_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      PAT: ${{ secrets.PAT }}
    steps:
      - uses: clusterflick/.github/setup@main
      - name: Set cache date
        run: echo "CACHE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Cache LLM responses
        uses: actions/cache@v5
        with:
          path: cache-llm
          key: cache-llm-${{ github.job }}-${{ env.CACHE_DATE }}
      - name: Download Retrieved Data
        uses: actions/download-artifact@v8
        with:
          name: retrieved-data
          path: retrieved-data/
          github-token: ${{ github.token }}
      - name: Download Historical Data
        uses: actions/download-artifact@v8
        with:
          name: combined-data
          path: combined-data/
          github-token: ${{ github.token }}

      - name: bfi.org.uk-imax
        run: npm run transform -- bfi.org.uk-imax
      - name: bfi.org.uk-southbank
        run: npm run transform -- bfi.org.uk-southbank

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: transform_bfi
          path: transformed-data/

  # ------------------------------------------------------------------------------
  # Transform Cineworld
  # ------------------------------------------------------------------------------
  transform_cineworld:
    name: Transform Cineworld
    needs: [download_retrieved_data, download_historical_data]
    runs-on: ubuntu-latest
    env:
      TZ: Europe/London
      MOVIEDB_API_KEY: ${{ secrets.MOVIEDB_API_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      PAT: ${{ secrets.PAT }}
    steps:
      - uses: clusterflick/.github/setup@main
      - name: Set cache date
        run: echo "CACHE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Cache LLM responses
        uses: actions/cache@v5
        with:
          path: cache-llm
          key: cache-llm-${{ github.job }}-${{ env.CACHE_DATE }}
      - name: Download Retrieved Data
        uses: actions/download-artifact@v8
        with:
          name: retrieved-data
          path: retrieved-data/
          github-token: ${{ github.token }}
      - name: Download Historical Data
        uses: actions/download-artifact@v8
        with:
          name: combined-data
          path: combined-data/
          github-token: ${{ github.token }}

      - name: cineworld.co.uk-bexleyheath
        run: npm run transform -- cineworld.co.uk-bexleyheath
      - name: cineworld.co.uk-enfield
        run: npm run transform -- cineworld.co.uk-enfield
      - name: cineworld.co.uk-feltham
        run: npm run transform -- cineworld.co.uk-feltham
      - name: cineworld.co.uk-hounslow
        run: npm run transform -- cineworld.co.uk-hounslow
      - name: cineworld.co.uk-ilford
        run: npm run transform -- cineworld.co.uk-ilford
      - name: cineworld.co.uk-leicester-square
        run: npm run transform -- cineworld.co.uk-leicester-square
      - name: cineworld.co.uk-south-ruislip
        run: npm run transform -- cineworld.co.uk-south-ruislip
      - name: cineworld.co.uk-the-o2-greenwich
        run: npm run transform -- cineworld.co.uk-the-o2-greenwich
      - name: cineworld.co.uk-wandsworth
        run: npm run transform -- cineworld.co.uk-wandsworth
      - name: cineworld.co.uk-wembley
        run: npm run transform -- cineworld.co.uk-wembley
      - name: cineworld.co.uk-west-india-quay
        run: npm run transform -- cineworld.co.uk-west-india-quay
      - name: cineworld.co.uk-wood-green
        run: npm run transform -- cineworld.co.uk-wood-green

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: transform_cineworld
          path: transformed-data/

  # ------------------------------------------------------------------------------
  # Transform Curzon
  # ------------------------------------------------------------------------------
  transform_curzon:
    name: Transform Curzon
    needs: [download_retrieved_data, download_historical_data]
    runs-on: ubuntu-latest
    env:
      TZ: Europe/London
      MOVIEDB_API_KEY: ${{ secrets.MOVIEDB_API_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      PAT: ${{ secrets.PAT }}
    steps:
      - uses: clusterflick/.github/setup@main
      - name: Set cache date
        run: echo "CACHE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Cache LLM responses
        uses: actions/cache@v5
        with:
          path: cache-llm
          key: cache-llm-${{ github.job }}-${{ env.CACHE_DATE }}
      - name: Download Retrieved Data
        uses: actions/download-artifact@v8
        with:
          name: retrieved-data
          path: retrieved-data/
          github-token: ${{ github.token }}
      - name: Download Historical Data
        uses: actions/download-artifact@v8
        with:
          name: combined-data
          path: combined-data/
          github-token: ${{ github.token }}

      - name: curzon.com-aldgate
        run: npm run transform -- curzon.com-aldgate
      - name: curzon.com-bloomsbury
        run: npm run transform -- curzon.com-bloomsbury
      - name: curzon.com-camden
        run: npm run transform -- curzon.com-camden
      - name: curzon.com-hoxton
        run: npm run transform -- curzon.com-hoxton
      - name: curzon.com-kingston
        run: npm run transform -- curzon.com-kingston
      - name: curzon.com-mayfair
        run: npm run transform -- curzon.com-mayfair
      - name: curzon.com-richmond
        run: npm run transform -- curzon.com-richmond
      - name: curzon.com-soho
        run: npm run transform -- curzon.com-soho
      - name: curzon.com-victoria
        run: npm run transform -- curzon.com-victoria
      - name: curzon.com-wimbledon
        run: npm run transform -- curzon.com-wimbledon
      - name: curzonseacontainers.com
        run: npm run transform -- curzonseacontainers.com

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: transform_curzon
          path: transformed-data/

  # ------------------------------------------------------------------------------
  # Transform Electric Cinema
  # ------------------------------------------------------------------------------
  transform_electric_cinema:
    name: Transform Electric Cinema
    needs: [download_retrieved_data, download_historical_data]
    runs-on: ubuntu-latest
    env:
      TZ: Europe/London
      MOVIEDB_API_KEY: ${{ secrets.MOVIEDB_API_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      PAT: ${{ secrets.PAT }}
    steps:
      - uses: clusterflick/.github/setup@main
      - name: Set cache date
        run: echo "CACHE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Cache LLM responses
        uses: actions/cache@v5
        with:
          path: cache-llm
          key: cache-llm-${{ github.job }}-${{ env.CACHE_DATE }}
      - name: Download Retrieved Data
        uses: actions/download-artifact@v8
        with:
          name: retrieved-data
          path: retrieved-data/
          github-token: ${{ github.token }}
      - name: Download Historical Data
        uses: actions/download-artifact@v8
        with:
          name: combined-data
          path: combined-data/
          github-token: ${{ github.token }}

      - name: electriccinema.co.uk-portobello
        run: npm run transform -- electriccinema.co.uk-portobello
      - name: electriccinema.co.uk-white-city
        run: npm run transform -- electriccinema.co.uk-white-city

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: transform_electric_cinema
          path: transformed-data/

  # ------------------------------------------------------------------------------
  # Transform Rooftop Cinema Club
  # ------------------------------------------------------------------------------
  transform_rooftopcinemaclub:
    name: Transform Rooftop Cinema Club
    needs: [download_retrieved_data, download_historical_data]
    runs-on: ubuntu-latest
    env:
      TZ: Europe/London
      MOVIEDB_API_KEY: ${{ secrets.MOVIEDB_API_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      PAT: ${{ secrets.PAT }}
    steps:
      - uses: clusterflick/.github/setup@main
      - name: Set cache date
        run: echo "CACHE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Cache LLM responses
        uses: actions/cache@v5
        with:
          path: cache-llm
          key: cache-llm-${{ github.job }}-${{ env.CACHE_DATE }}
      - name: Download Retrieved Data
        uses: actions/download-artifact@v8
        with:
          name: retrieved-data
          path: retrieved-data/
          github-token: ${{ github.token }}
      - name: Download Historical Data
        uses: actions/download-artifact@v8
        with:
          name: combined-data
          path: combined-data/
          github-token: ${{ github.token }}

      - name: rooftopcinemaclub.com-peckham
        run: npm run transform -- rooftopcinemaclub.com-peckham
      - name: rooftopcinemaclub.com-stratford
        run: npm run transform -- rooftopcinemaclub.com-stratford

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: transform_rooftopcinemaclub
          path: transformed-data/

  # ------------------------------------------------------------------------------
  # Transform Tate
  # ------------------------------------------------------------------------------
  transform_tate:
    name: Transform Tate
    needs: [download_retrieved_data, download_historical_data]
    runs-on: ubuntu-latest
    env:
      TZ: Europe/London
      MOVIEDB_API_KEY: ${{ secrets.MOVIEDB_API_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      PAT: ${{ secrets.PAT }}
    steps:
      - uses: clusterflick/.github/setup@main
      - name: Set cache date
        run: echo "CACHE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Cache LLM responses
        uses: actions/cache@v5
        with:
          path: cache-llm
          key: cache-llm-${{ github.job }}-${{ env.CACHE_DATE }}
      - name: Download Retrieved Data
        uses: actions/download-artifact@v8
        with:
          name: retrieved-data
          path: retrieved-data/
          github-token: ${{ github.token }}
      - name: Download Historical Data
        uses: actions/download-artifact@v8
        with:
          name: combined-data
          path: combined-data/
          github-token: ${{ github.token }}

      - name: tate.org.uk-tate-britain
        run: npm run transform -- tate.org.uk-tate-britain
      - name: tate.org.uk-tate-modern
        run: npm run transform -- tate.org.uk-tate-modern

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: transform_tate
          path: transformed-data/

  # ------------------------------------------------------------------------------
  # Transform Firmdale Hotels
  # ------------------------------------------------------------------------------
  transform_firmdale_hotels:
    name: Transform Firmdale Hotels
    needs: [download_retrieved_data, download_historical_data]
    runs-on: ubuntu-latest
    env:
      TZ: Europe/London
      MOVIEDB_API_KEY: ${{ secrets.MOVIEDB_API_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      PAT: ${{ secrets.PAT }}
    steps:
      - uses: clusterflick/.github/setup@main
      - name: Set cache date
        run: echo "CACHE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Cache LLM responses
        uses: actions/cache@v5
        with:
          path: cache-llm
          key: cache-llm-${{ github.job }}-${{ env.CACHE_DATE }}
      - name: Download Retrieved Data
        uses: actions/download-artifact@v8
        with:
          name: retrieved-data
          path: retrieved-data/
          github-token: ${{ github.token }}
      - name: Download Historical Data
        uses: actions/download-artifact@v8
        with:
          name: combined-data
          path: combined-data/
          github-token: ${{ github.token }}

      - name: firmdalehotels.com-charlotte-street
        run: npm run transform -- firmdalehotels.com-charlotte-street
      - name: firmdalehotels.com-covent-garden
        run: npm run transform -- firmdalehotels.com-covent-garden
      - name: firmdalehotels.com-soho
        run: npm run transform -- firmdalehotels.com-soho

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: transform_firmdale_hotels
          path: transformed-data/

  # ------------------------------------------------------------------------------
  # Transform Everyman
  # ------------------------------------------------------------------------------
  transform_everyman:
    name: Transform Everyman
    needs: [download_retrieved_data, download_historical_data]
    runs-on: ubuntu-latest
    env:
      TZ: Europe/London
      MOVIEDB_API_KEY: ${{ secrets.MOVIEDB_API_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      PAT: ${{ secrets.PAT }}
    steps:
      - uses: clusterflick/.github/setup@main
      - name: Set cache date
        run: echo "CACHE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Cache LLM responses
        uses: actions/cache@v5
        with:
          path: cache-llm
          key: cache-llm-${{ github.job }}-${{ env.CACHE_DATE }}
      - name: Download Retrieved Data
        uses: actions/download-artifact@v8
        with:
          name: retrieved-data
          path: retrieved-data/
          github-token: ${{ github.token }}
      - name: Download Historical Data
        uses: actions/download-artifact@v8
        with:
          name: combined-data
          path: combined-data/
          github-token: ${{ github.token }}

      - name: everymancinema.com-baker-street
        run: npm run transform -- everymancinema.com-baker-street
      - name: everymancinema.com-barnet
        run: npm run transform -- everymancinema.com-barnet
      - name: everymancinema.com-belsize-park
        run: npm run transform -- everymancinema.com-belsize-park
      - name: everymancinema.com-borough-yards
        run: npm run transform -- everymancinema.com-borough-yards
      - name: everymancinema.com-brentford
        run: npm run transform -- everymancinema.com-brentford
      - name: everymancinema.com-broadgate
        run: npm run transform -- everymancinema.com-broadgate
      - name: everymancinema.com-canary-wharf
        run: npm run transform -- everymancinema.com-canary-wharf
      - name: everymancinema.com-chelsea
        run: npm run transform -- everymancinema.com-chelsea
      - name: everymancinema.com-crystal-palace
        run: npm run transform -- everymancinema.com-crystal-palace
      - name: everymancinema.com-everyman-on-the-canal-at-kings-cross
        run: npm run transform -- everymancinema.com-everyman-on-the-canal-at-kings-cross
      - name: everymancinema.com-hampstead
        run: npm run transform -- everymancinema.com-hampstead
      - name: everymancinema.com-kings-cross
        run: npm run transform -- everymancinema.com-kings-cross
      - name: everymancinema.com-maida-vale
        run: npm run transform -- everymancinema.com-maida-vale
      - name: everymancinema.com-muswell-hill
        run: npm run transform -- everymancinema.com-muswell-hill
      - name: everymancinema.com-screen-on-the-green
        run: npm run transform -- everymancinema.com-screen-on-the-green
      - name: everymancinema.com-stratford-international
        run: npm run transform -- everymancinema.com-stratford-international
      - name: everymancinema.com-the-whiteley
        run: npm run transform -- everymancinema.com-the-whiteley

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: transform_everyman
          path: transformed-data/

  # ------------------------------------------------------------------------------
  # Transform Vue
  # ------------------------------------------------------------------------------
  transform_vue:
    name: Transform Vue
    needs: [download_retrieved_data, download_historical_data]
    runs-on: ubuntu-latest
    env:
      TZ: Europe/London
      MOVIEDB_API_KEY: ${{ secrets.MOVIEDB_API_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      PAT: ${{ secrets.PAT }}
    steps:
      - uses: clusterflick/.github/setup@main
      - name: Set cache date
        run: echo "CACHE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Cache LLM responses
        uses: actions/cache@v5
        with:
          path: cache-llm
          key: cache-llm-${{ github.job }}-${{ env.CACHE_DATE }}
      - name: Download Retrieved Data
        uses: actions/download-artifact@v8
        with:
          name: retrieved-data
          path: retrieved-data/
          github-token: ${{ github.token }}
      - name: Download Historical Data
        uses: actions/download-artifact@v8
        with:
          name: combined-data
          path: combined-data/
          github-token: ${{ github.token }}

      - name: myvue.com-bromley
        run: npm run transform -- myvue.com-bromley
      - name: myvue.com-croydon-purley-way
        run: npm run transform -- myvue.com-croydon-purley-way
      - name: myvue.com-dagenham
        run: npm run transform -- myvue.com-dagenham
      - name: myvue.com-eltham
        run: npm run transform -- myvue.com-eltham
      - name: myvue.com-finchley-road
        run: npm run transform -- myvue.com-finchley-road
      - name: myvue.com-fulham-broadway
        run: npm run transform -- myvue.com-fulham-broadway
      - name: myvue.com-harrow
        run: npm run transform -- myvue.com-harrow
      - name: myvue.com-islington
        run: npm run transform -- myvue.com-islington
      - name: myvue.com-leicester-square
        run: npm run transform -- myvue.com-leicester-square
      - name: myvue.com-north-finchley
        run: npm run transform -- myvue.com-north-finchley
      - name: myvue.com-piccadilly
        run: npm run transform -- myvue.com-piccadilly
      - name: myvue.com-romford
        run: npm run transform -- myvue.com-romford
      - name: myvue.com-westfield
        run: npm run transform -- myvue.com-westfield
      - name: myvue.com-westfield-stratford-city
        run: npm run transform -- myvue.com-westfield-stratford-city
      - name: myvue.com-wood-green
        run: npm run transform -- myvue.com-wood-green

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: transform_vue
          path: transformed-data/

  # ------------------------------------------------------------------------------
  # Transform ODEON
  # ------------------------------------------------------------------------------
  transform_odeon:
    name: Transform ODEON
    needs: [download_retrieved_data, download_historical_data]
    runs-on: ubuntu-latest
    env:
      TZ: Europe/London
      MOVIEDB_API_KEY: ${{ secrets.MOVIEDB_API_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      PAT: ${{ secrets.PAT }}
    steps:
      - uses: clusterflick/.github/setup@main
      - name: Set cache date
        run: echo "CACHE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Cache LLM responses
        uses: actions/cache@v5
        with:
          path: cache-llm
          key: cache-llm-${{ github.job }}-${{ env.CACHE_DATE }}
      - name: Download Retrieved Data
        uses: actions/download-artifact@v8
        with:
          name: retrieved-data
          path: retrieved-data/
          github-token: ${{ github.token }}
      - name: Download Historical Data
        uses: actions/download-artifact@v8
        with:
          name: combined-data
          path: combined-data/
          github-token: ${{ github.token }}

      - name: odeon.co.uk-acton
        run: npm run transform -- odeon.co.uk-acton
      - name: odeon.co.uk-beckenham
        run: npm run transform -- odeon.co.uk-beckenham
      - name: odeon.co.uk-greenwich
        run: npm run transform -- odeon.co.uk-greenwich
      - name: odeon.co.uk-haymarket
        run: npm run transform -- odeon.co.uk-haymarket
      - name: odeon.co.uk-holloway
        run: npm run transform -- odeon.co.uk-holloway
      - name: odeon.co.uk-islington
        run: npm run transform -- odeon.co.uk-islington
      - name: odeon.co.uk-kingston
        run: npm run transform -- odeon.co.uk-kingston
      - name: odeon.co.uk-lee-valley
        run: npm run transform -- odeon.co.uk-lee-valley
      - name: odeon.co.uk-leicester-square
        run: npm run transform -- odeon.co.uk-leicester-square
      - name: odeon.co.uk-orpington
        run: npm run transform -- odeon.co.uk-orpington
      - name: odeon.co.uk-putney
        run: npm run transform -- odeon.co.uk-putney
      - name: odeon.co.uk-richmond
        run: npm run transform -- odeon.co.uk-richmond
      - name: odeon.co.uk-south-woodford
        run: npm run transform -- odeon.co.uk-south-woodford
      - name: odeon.co.uk-streatham
        run: npm run transform -- odeon.co.uk-streatham
      - name: odeon.co.uk-swiss-cottage
        run: npm run transform -- odeon.co.uk-swiss-cottage
      - name: odeon.co.uk-tottenham-court-road
        run: npm run transform -- odeon.co.uk-tottenham-court-road
      - name: odeon.co.uk-uxbridge
        run: npm run transform -- odeon.co.uk-uxbridge
      - name: odeon.co.uk-west-end
        run: npm run transform -- odeon.co.uk-west-end
      - name: odeon.co.uk-wimbledon
        run: npm run transform -- odeon.co.uk-wimbledon

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: transform_odeon
          path: transformed-data/

  # ------------------------------------------------------------------------------
  # Transform Picturehouses
  # ------------------------------------------------------------------------------
  transform_picturehouses:
    name: Transform Picturehouses
    needs: [download_retrieved_data, download_historical_data]
    runs-on: ubuntu-latest
    env:
      TZ: Europe/London
      MOVIEDB_API_KEY: ${{ secrets.MOVIEDB_API_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      PAT: ${{ secrets.PAT }}
    steps:
      - uses: clusterflick/.github/setup@main
      - name: Set cache date
        run: echo "CACHE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Cache LLM responses
        uses: actions/cache@v5
        with:
          path: cache-llm
          key: cache-llm-${{ github.job }}-${{ env.CACHE_DATE }}
      - name: Download Retrieved Data
        uses: actions/download-artifact@v8
        with:
          name: retrieved-data
          path: retrieved-data/
          github-token: ${{ github.token }}
      - name: Download Historical Data
        uses: actions/download-artifact@v8
        with:
          name: combined-data
          path: combined-data/
          github-token: ${{ github.token }}

      - name: picturehouses.com-central
        run: npm run transform -- picturehouses.com-central
      - name: picturehouses.com-clapham
        run: npm run transform -- picturehouses.com-clapham
      - name: picturehouses.com-crouch-end
        run: npm run transform -- picturehouses.com-crouch-end
      - name: picturehouses.com-ealing
        run: npm run transform -- picturehouses.com-ealing
      - name: picturehouses.com-east-dulwich
        run: npm run transform -- picturehouses.com-east-dulwich
      - name: picturehouses.com-greenwich
        run: npm run transform -- picturehouses.com-greenwich
      - name: picturehouses.com-finsbury-park
        run: npm run transform -- picturehouses.com-finsbury-park
      - name: picturehouses.com-hackney
        run: npm run transform -- picturehouses.com-hackney
      - name: picturehouses.com-the-gate
        run: npm run transform -- picturehouses.com-the-gate
      - name: picturehouses.com-the-ritzy
        run: npm run transform -- picturehouses.com-the-ritzy
      - name: picturehouses.com-west-norwood
        run: npm run transform -- picturehouses.com-west-norwood

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: transform_picturehouses
          path: transformed-data/

  # ------------------------------------------------------------------------------
  # Transform cinema organisations (Part 1)
  # ------------------------------------------------------------------------------
  transform_organisations_1:
    name: Transform Organisations 1
    needs: [download_retrieved_data, download_historical_data]
    runs-on: ubuntu-latest
    env:
      TZ: Europe/London
      MOVIEDB_API_KEY: ${{ secrets.MOVIEDB_API_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      PAT: ${{ secrets.PAT }}
    steps:
      - uses: clusterflick/.github/setup@main
      - name: Set cache date
        run: echo "CACHE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Cache LLM responses
        uses: actions/cache@v5
        with:
          path: cache-llm
          key: cache-llm-${{ github.job }}-${{ env.CACHE_DATE }}
      - name: Download Retrieved Data
        uses: actions/download-artifact@v8
        with:
          name: retrieved-data
          path: retrieved-data/
          github-token: ${{ github.token }}
      - name: Download Historical Data
        uses: actions/download-artifact@v8
        with:
          name: combined-data
          path: combined-data/
          github-token: ${{ github.token }}

      - name: barbican.org.uk
        run: npm run transform -- barbican.org.uk
      - name: cinemamuseum.org.uk
        run: npm run transform -- cinemamuseum.org.uk
      - name: riversidestudios.co.uk
        run: npm run transform -- riversidestudios.co.uk
      - name: sciencemuseum.org.uk
        run: npm run transform -- sciencemuseum.org.uk
      - name: ica.art
        run: npm run transform -- ica.art

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: transform_organisations_1
          path: transformed-data/

  # ------------------------------------------------------------------------------
  # Transform cinema organisations (Part 2)
  # ------------------------------------------------------------------------------
  transform_organisations_2:
    name: Transform Organisations 2
    needs: [download_retrieved_data, download_historical_data]
    runs-on: ubuntu-latest
    env:
      TZ: Europe/London
      MOVIEDB_API_KEY: ${{ secrets.MOVIEDB_API_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      PAT: ${{ secrets.PAT }}
    steps:
      - uses: clusterflick/.github/setup@main
      - name: Set cache date
        run: echo "CACHE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Cache LLM responses
        uses: actions/cache@v5
        with:
          path: cache-llm
          key: cache-llm-${{ github.job }}-${{ env.CACHE_DATE }}
      - name: Download Retrieved Data
        uses: actions/download-artifact@v8
        with:
          name: retrieved-data
          path: retrieved-data/
          github-token: ${{ github.token }}
      - name: Download Historical Data
        uses: actions/download-artifact@v8
        with:
          name: combined-data
          path: combined-data/
          github-token: ${{ github.token }}

      - name: institut-francais.org.uk
        run: npm run transform -- institut-francais.org.uk
      - name: jw3.org.uk
        run: npm run transform -- jw3.org.uk
      - name: princecharlescinema.com
        run: npm run transform -- princecharlescinema.com
      - name: genesiscinema.co.uk
        run: npm run transform -- genesiscinema.co.uk

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: transform_organisations_2
          path: transformed-data/

  # ------------------------------------------------------------------------------
  # Transform cinemas which rely on external event sources (Part 1)
  # ------------------------------------------------------------------------------
  transform_external_events_1:
    name: Transform External Events 1
    needs: [download_retrieved_data, download_historical_data]
    runs-on: ubuntu-latest
    env:
      TZ: Europe/London
      MOVIEDB_API_KEY: ${{ secrets.MOVIEDB_API_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      PAT: ${{ secrets.PAT }}
    steps:
      - uses: clusterflick/.github/setup@main
      - name: Set cache date
        run: echo "CACHE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Cache LLM responses
        uses: actions/cache@v5
        with:
          path: cache-llm
          key: cache-llm-${{ github.job }}-${{ env.CACHE_DATE }}
      - name: Download Retrieved Data
        uses: actions/download-artifact@v8
        with:
          name: retrieved-data
          path: retrieved-data/
          github-token: ${{ github.token }}
      - name: Download Historical Data
        uses: actions/download-artifact@v8
        with:
          name: combined-data
          path: combined-data/
          github-token: ${{ github.token }}

      - name: allisjoysoho.com
        run: npm run transform -- allisjoysoho.com
      - name: beermerchantstap.com
        run: npm run transform -- beermerchantstap.com
      - name: freud.org.uk
        run: npm run transform -- freud.org.uk
      - name: pelicanhouse.org
        run: npm run transform -- pelicanhouse.org
      - name: artotel.com-battersea-power-station
        run: npm run transform -- artotel.com-battersea-power-station
      - name: artotel.com-hoxton
        run: npm run transform -- artotel.com-hoxton
      - name: claphamgrand.com
        run: npm run transform -- claphamgrand.com
      - name: rivoliballroom.com
        run: npm run transform -- rivoliballroom.com
      - name: beehiven17.com
        run: npm run transform -- beehiven17.com
      - name: boxpark.co.uk-wembley
        run: npm run transform -- boxpark.co.uk-wembley
      - name: frontlineclub.com
        run: npm run transform -- frontlineclub.com
      - name: ivyhousenunhead.com
        run: npm run transform -- ivyhousenunhead.com
      - name: rocketvan.co.uk
        run: npm run transform -- rocketvan.co.uk
      - name: theatreship.co.uk
        run: npm run transform -- theatreship.co.uk
      - name: imperial.ac.uk
        run: npm run transform -- imperial.ac.uk
      - name: culture.hu-london
        run: npm run transform -- culture.hu-london
      - name: kerbsocialclub.com
        run: npm run transform -- kerbsocialclub.com
      - name: lambeth.gov.uk-vauxhall-pleasure-gardens
        run: npm run transform -- lambeth.gov.uk-vauxhall-pleasure-gardens

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: transform_external_events_1
          path: transformed-data/

  # ------------------------------------------------------------------------------
  # Transform cinemas which rely on external event sources (Part 2)
  # ------------------------------------------------------------------------------
  transform_external_events_2:
    name: Transform External Events 2
    needs: [download_retrieved_data, download_historical_data]
    runs-on: ubuntu-latest
    env:
      TZ: Europe/London
      MOVIEDB_API_KEY: ${{ secrets.MOVIEDB_API_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      PAT: ${{ secrets.PAT }}
    steps:
      - uses: clusterflick/.github/setup@main
      - name: Set cache date
        run: echo "CACHE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Cache LLM responses
        uses: actions/cache@v5
        with:
          path: cache-llm
          key: cache-llm-${{ github.job }}-${{ env.CACHE_DATE }}
      - name: Download Retrieved Data
        uses: actions/download-artifact@v8
        with:
          name: retrieved-data
          path: retrieved-data/
          github-token: ${{ github.token }}
      - name: Download Historical Data
        uses: actions/download-artifact@v8
        with:
          name: combined-data
          path: combined-data/
          github-token: ${{ github.token }}

      - name: uel.ac.uk-the-source
        run: npm run transform -- uel.ac.uk-the-source
      - name: bfi.org.uk-stephen-street
        run: npm run transform -- bfi.org.uk-stephen-street
      - name: goethe.de
        run: npm run transform -- goethe.de
      - name: marriott.com-w-london
        run: npm run transform -- marriott.com-w-london
      - name: mason-fifth.com-westbourne-park
        run: npm run transform -- mason-fifth.com-westbourne-park
      - name: ronspeckham.com
        run: npm run transform -- ronspeckham.com
      - name: theexhibit.co.uk
        run: npm run transform -- theexhibit.co.uk
      - name: castlehaven.org.uk
        run: npm run transform -- castlehaven.org.uk
      - name: japanhouselondon.uk
        run: npm run transform -- japanhouselondon.uk
      - name: chcc.org.uk
        run: npm run transform -- chcc.org.uk
      - name: crick.ac.uk
        run: npm run transform -- crick.ac.uk
      - name: fellowshipinn.co.uk
        run: npm run transform -- fellowshipinn.co.uk
      - name: finchcafe.co.uk
        run: npm run transform -- finchcafe.co.uk
      - name: islington.gov.uk-black-cultural-centre
        run: npm run transform -- islington.gov.uk-black-cultural-centre
      - name: thehenandchickenstheatrebar.co.uk
        run: npm run transform -- thehenandchickenstheatrebar.co.uk
      - name: londonwelsh.org
        run: npm run transform -- londonwelsh.org
      - name: london.czechcentres.cz
        run: npm run transform -- london.czechcentres.cz
      - name: nehrucentre.org.uk
        run: npm run transform -- nehrucentre.org.uk

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: transform_external_events_2
          path: transformed-data/

  # ------------------------------------------------------------------------------
  # Transform cinemas which rely on external event sources (Part 3)
  # ------------------------------------------------------------------------------
  transform_external_events_3:
    name: Transform External Events 3
    needs: [download_retrieved_data, download_historical_data]
    runs-on: ubuntu-latest
    env:
      TZ: Europe/London
      MOVIEDB_API_KEY: ${{ secrets.MOVIEDB_API_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      PAT: ${{ secrets.PAT }}
    steps:
      - uses: clusterflick/.github/setup@main
      - name: Set cache date
        run: echo "CACHE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Cache LLM responses
        uses: actions/cache@v5
        with:
          path: cache-llm
          key: cache-llm-${{ github.job }}-${{ env.CACHE_DATE }}
      - name: Download Retrieved Data
        uses: actions/download-artifact@v8
        with:
          name: retrieved-data
          path: retrieved-data/
          github-token: ${{ github.token }}
      - name: Download Historical Data
        uses: actions/download-artifact@v8
        with:
          name: combined-data
          path: combined-data/
          github-token: ${{ github.token }}

      - name: gold.ac.uk
        run: npm run transform -- gold.ac.uk
      - name: islington.gov.uk-islington-museum
        run: npm run transform -- islington.gov.uk-islington-museum
      - name: kcl.ac.uk-strand
        run: npm run transform -- kcl.ac.uk-strand
      - name: khccc.com
        run: npm run transform -- khccc.com
      - name: metrolandcultures.com
        run: npm run transform -- metrolandcultures.com
      - name: myheathway.com
        run: npm run transform -- myheathway.com
      - name: newtownculture.org-womens-museum
        run: npm run transform -- newtownculture.org-womens-museum
      - name: princeofpeckham.co.uk
        run: npm run transform -- princeofpeckham.co.uk
      - name: better.org.uk-croydon-sports-arena
        run: npm run transform -- better.org.uk-croydon-sports-arena
      - name: dalstonsuperstore.com
        run: npm run transform -- dalstonsuperstore.com
      - name: ethicalproperty.co.uk-the-green-house
        run: npm run transform -- ethicalproperty.co.uk-the-green-house
      - name: william-the-fourth.com
        run: npm run transform -- william-the-fourth.com
      - name: thewildsbarkingriverside.london
        run: npm run transform -- thewildsbarkingriverside.london
      - name: peckhamlevels.org
        run: npm run transform -- peckhamlevels.org
      - name: rbkc.gov.uk-kensington-central-library
        run: npm run transform -- rbkc.gov.uk-kensington-central-library
      - name: callypark.london
        run: npm run transform -- callypark.london
      - name: commonpress.co.uk
        run: npm run transform -- commonpress.co.uk
      - name: etceteratheatrecamden.com
        run: npm run transform -- etceteratheatrecamden.com
      - name: fen-court.com
        run: npm run transform -- fen-court.com
      - name: berniegrantcentre.co.uk
        run: npm run transform -- berniegrantcentre.co.uk
      - name: camouflagecafe.co.uk
        run: npm run transform -- camouflagecafe.co.uk
      - name: conwayhall.org.uk
        run: npm run transform -- conwayhall.org.uk
      - name: earthackney.co.uk
        run: npm run transform -- earthackney.co.uk
      - name: enfield.gov.uk-angel-community-centre
        run: npm run transform -- enfield.gov.uk-angel-community-centre
      - name: greenfordquay.com
        run: npm run transform -- greenfordquay.com
      - name: harrisinstitute.org.uk
        run: npm run transform -- harrisinstitute.org.uk
      - name: ladbrokehall.com
        run: npm run transform -- ladbrokehall.com
      - name: thebrookmill.co.uk
        run: npm run transform -- thebrookmill.co.uk

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: transform_external_events_3
          path: transformed-data/

  # ------------------------------------------------------------------------------
  # Transform cinemas which rely on external event sources (Part 4)
  # ------------------------------------------------------------------------------
  transform_external_events_4:
    name: Transform External Events 4
    needs: [download_retrieved_data, download_historical_data]
    runs-on: ubuntu-latest
    env:
      TZ: Europe/London
      MOVIEDB_API_KEY: ${{ secrets.MOVIEDB_API_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      PAT: ${{ secrets.PAT }}
    steps:
      - uses: clusterflick/.github/setup@main
      - name: Set cache date
        run: echo "CACHE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Cache LLM responses
        uses: actions/cache@v5
        with:
          path: cache-llm
          key: cache-llm-${{ github.job }}-${{ env.CACHE_DATE }}
      - name: Download Retrieved Data
        uses: actions/download-artifact@v8
        with:
          name: retrieved-data
          path: retrieved-data/
          github-token: ${{ github.token }}
      - name: Download Historical Data
        uses: actions/download-artifact@v8
        with:
          name: combined-data
          path: combined-data/
          github-token: ${{ github.token }}

      - name: exchangetwickenham.co.uk
        run: npm run transform -- exchangetwickenham.co.uk
      - name: langleyfilmbox.com
        run: npm run transform -- langleyfilmbox.com
      - name: scrt.onl
        run: npm run transform -- scrt.onl
      - name: sohoscreeningrooms.co.uk
        run: npm run transform -- sohoscreeningrooms.co.uk
      - name: thexchange.org.uk
        run: npm run transform -- thexchange.org.uk
      - name: uk.kef.com
        run: npm run transform -- uk.kef.com
      - name: irishculturalcentre.co.uk
        run: npm run transform -- irishculturalcentre.co.uk
      - name: boathousebarkingstudios.com
        run: npm run transform -- boathousebarkingstudios.com
      - name: feministlibrary.co.uk
        run: npm run transform -- feministlibrary.co.uk
      - name: goodhotel.co-london
        run: npm run transform -- goodhotel.co-london
      - name: aplaceforchange.co.uk
        run: npm run transform -- aplaceforchange.co.uk
      - name: mothclub.co.uk
        run: npm run transform -- mothclub.co.uk
      - name: lux.org.uk
        run: npm run transform -- lux.org.uk
      - name: rca.ac.uk-battersea
        run: npm run transform -- rca.ac.uk-battersea
      - name: rca.ac.uk-kensington
        run: npm run transform -- rca.ac.uk-kensington
      - name: hackneyshowroom.com
        run: npm run transform -- hackneyshowroom.com
      - name: labs.thedrum.com
        run: npm run transform -- labs.thedrum.com
      - name: littlenans.co.uk-2-0
        run: npm run transform -- littlenans.co.uk-2-0
      - name: londonartbar.com
        run: npm run transform -- londonartbar.com

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: transform_external_events_4
          path: transformed-data/

  # ------------------------------------------------------------------------------
  # Transform cinemas which rely on external event sources (Part 5)
  # ------------------------------------------------------------------------------
  transform_external_events_5:
    name: Transform External Events 5
    needs: [download_retrieved_data, download_historical_data]
    runs-on: ubuntu-latest
    env:
      TZ: Europe/London
      MOVIEDB_API_KEY: ${{ secrets.MOVIEDB_API_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      PAT: ${{ secrets.PAT }}
    steps:
      - uses: clusterflick/.github/setup@main
      - name: Set cache date
        run: echo "CACHE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Cache LLM responses
        uses: actions/cache@v5
        with:
          path: cache-llm
          key: cache-llm-${{ github.job }}-${{ env.CACHE_DATE }}
      - name: Download Retrieved Data
        uses: actions/download-artifact@v8
        with:
          name: retrieved-data
          path: retrieved-data/
          github-token: ${{ github.token }}
      - name: Download Historical Data
        uses: actions/download-artifact@v8
        with:
          name: combined-data
          path: combined-data/
          github-token: ${{ github.token }}

      - name: qmul.ac.uk-bloc
        run: npm run transform -- qmul.ac.uk-bloc
      - name: thersa.org
        run: npm run transform -- thersa.org
      - name: ucl.ac.uk-ucl-east-community-cinema
        run: npm run transform -- ucl.ac.uk-ucl-east-community-cinema
      - name: courthouse-hotel.com-shoreditch
        run: npm run transform -- courthouse-hotel.com-shoreditch
      - name: courthouse-hotel.com-soho
        run: npm run transform -- courthouse-hotel.com-soho
      - name: facebook.com-thehaggerston
        run: npm run transform -- facebook.com-thehaggerston
      - name: signaturebrew.co.uk-blackhorseroad
        run: npm run transform -- signaturebrew.co.uk-blackhorseroad
      - name: walthamforest.gov.uk
        run: npm run transform -- walthamforest.gov.uk
      - name: bulgarihotels.com
        run: npm run transform -- bulgarihotels.com
      - name: cine-real.com
        run: npm run transform -- cine-real.com
      - name: piehousecoop.co.uk
        run: npm run transform -- piehousecoop.co.uk
      - name: professional.dolby.com-soho
        run: npm run transform -- professional.dolby.com-soho
      - name: setspace.uk
        run: npm run transform -- setspace.uk
      - name: thcentre.com
        run: npm run transform -- thcentre.com
      - name: uel.ac.uk-univeristy-square-stratford
        run: npm run transform -- uel.ac.uk-univeristy-square-stratford
      - name: newcrossinn.com
        run: npm run transform -- newcrossinn.com
      - name: phonicarecords.com
        run: npm run transform -- phonicarecords.com
      - name: southlondongallery.org
        run: npm run transform -- southlondongallery.org
      - name: theeaglehoxton.co.uk
        run: npm run transform -- theeaglehoxton.co.uk
      - name: writersroom.org.uk
        run: npm run transform -- writersroom.org.uk

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: transform_external_events_5
          path: transformed-data/

  # ------------------------------------------------------------------------------
  # Transform cinemas which rely on external event sources (Part 6)
  # ------------------------------------------------------------------------------
  transform_external_events_6:
    name: Transform External Events 6
    needs: [download_retrieved_data, download_historical_data]
    runs-on: ubuntu-latest
    env:
      TZ: Europe/London
      MOVIEDB_API_KEY: ${{ secrets.MOVIEDB_API_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      PAT: ${{ secrets.PAT }}
    steps:
      - uses: clusterflick/.github/setup@main
      - name: Set cache date
        run: echo "CACHE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Cache LLM responses
        uses: actions/cache@v5
        with:
          path: cache-llm
          key: cache-llm-${{ github.job }}-${{ env.CACHE_DATE }}
      - name: Download Retrieved Data
        uses: actions/download-artifact@v8
        with:
          name: retrieved-data
          path: retrieved-data/
          github-token: ${{ github.token }}
      - name: Download Historical Data
        uses: actions/download-artifact@v8
        with:
          name: combined-data
          path: combined-data/
          github-token: ${{ github.token }}

      - name: themayfairhotel.co.uk
        run: npm run transform -- themayfairhotel.co.uk
      - name: reinstate.info
        run: npm run transform -- reinstate.info
      - name: scarlettmalone.com-subtitlecinema
        run: npm run transform -- scarlettmalone.com-subtitlecinema
      - name: shaispace.com
        run: npm run transform -- shaispace.com
      - name: strongroombar.com
        run: npm run transform -- strongroombar.com
      - name: thamesmeadnow.org.uk-the-nest
        run: npm run transform -- thamesmeadnow.org.uk-the-nest
      - name: thethomaswallcentre.harleystreethypnosis.co.uk
        run: npm run transform -- thethomaswallcentre.harleystreethypnosis.co.uk
      - name: ucl.ac.uk-bentham-house
        run: npm run transform -- ucl.ac.uk-bentham-house
      - name: ucl.ac.uk-ssees
        run: npm run transform -- ucl.ac.uk-ssees
      - name: stmarys.ac.uk-the-1850
        run: npm run transform -- stmarys.ac.uk-the-1850
      - name: thedivine.co.uk
        run: npm run transform -- thedivine.co.uk
      - name: triangledeptford.org
        run: npm run transform -- triangledeptford.org
      - name: thegreennunhead.org
        run: npm run transform -- thegreennunhead.org
      - name: vaginamuseum.co.uk
        run: npm run transform -- vaginamuseum.co.uk
      - name: wienerholocaustlibrary.org
        run: npm run transform -- wienerholocaustlibrary.org
      - name: objetstrouves.co.uk
        run: npm run transform -- objetstrouves.co.uk
      - name: stmchurch.co.uk
        run: npm run transform -- stmchurch.co.uk
      - name: 229.london
        run: npm run transform -- 229.london
      - name: drakeandmorgan.co.uk-the-refinery-citypoint
        run: npm run transform -- drakeandmorgan.co.uk-the-refinery-citypoint
      - name: drakeandmorgan.co.uk-the-moniker
        run: npm run transform -- drakeandmorgan.co.uk-the-moniker
      - name: parlourkensal.com
        run: npm run transform -- parlourkensal.com
      - name: thevinenw5.co.uk
        run: npm run transform -- thevinenw5.co.uk
      - name: contactthecaveldn.wixsite.com
        run: npm run transform -- contactthecaveldn.wixsite.com
      - name: otterchaos.co.uk
        run: npm run transform -- otterchaos.co.uk
      - name: walthamstowtradeshall.com
        run: npm run transform -- walthamstowtradeshall.com
      - name: newingtongreenmeetinghouse.org.uk
        run: npm run transform -- newingtongreenmeetinghouse.org.uk
      - name: allsaintsislington.org
        run: npm run transform -- allsaintsislington.org
      - name: hyphastudios.com-kentish-town
        run: npm run transform -- hyphastudios.com-kentish-town

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: transform_external_events_6
          path: transformed-data/

  # ------------------------------------------------------------------------------
  # Transform cinemas which rely on external event sources (Part 7)
  # ------------------------------------------------------------------------------
  transform_external_events_7:
    name: Transform External Events 7
    needs: [download_retrieved_data, download_historical_data]
    runs-on: ubuntu-latest
    env:
      TZ: Europe/London
      MOVIEDB_API_KEY: ${{ secrets.MOVIEDB_API_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      PAT: ${{ secrets.PAT }}
    steps:
      - uses: clusterflick/.github/setup@main
      - name: Set cache date
        run: echo "CACHE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Cache LLM responses
        uses: actions/cache@v5
        with:
          path: cache-llm
          key: cache-llm-${{ github.job }}-${{ env.CACHE_DATE }}
      - name: Download Retrieved Data
        uses: actions/download-artifact@v8
        with:
          name: retrieved-data
          path: retrieved-data/
          github-token: ${{ github.token }}
      - name: Download Historical Data
        uses: actions/download-artifact@v8
        with:
          name: combined-data
          path: combined-data/
          github-token: ${{ github.token }}

      - name: hausulondon.co.uk
        run: npm run transform -- hausulondon.co.uk
      - name: theleytonengineer.co.uk
        run: npm run transform -- theleytonengineer.co.uk
      - name: sanctumsoho.com
        run: npm run transform -- sanctumsoho.com
      - name: wansteadfringe.org-the-wanstead-curtain
        run: npm run transform -- wansteadfringe.org-the-wanstead-curtain
      - name: lanzaroteworks.com
        run: npm run transform -- lanzaroteworks.com
      - name: hounslow.gov.uk-heston-park
        run: npm run transform -- hounslow.gov.uk-heston-park
      - name: hounslow.gov.uk-feltham-park
        run: npm run transform -- hounslow.gov.uk-feltham-park
      - name: hounslow.gov.uk-thornbury-playing-fields
        run: npm run transform -- hounslow.gov.uk-thornbury-playing-fields
      - name: lowermarshmarket.com
        run: npm run transform -- lowermarshmarket.com
      - name: stlawrencejewry.org.uk
        run: npm run transform -- stlawrencejewry.org.uk
      - name: stkatharinecree.org
        run: npm run transform -- stkatharinecree.org
      - name: spitalfields.church
        run: npm run transform -- spitalfields.church
      - name: bloomsbury.org.uk
        run: npm run transform -- bloomsbury.org.uk
      - name: rosslynhillchapel.org.uk
        run: npm run transform -- rosslynhillchapel.org.uk
      - name: wpp.com-sea-containers
        run: npm run transform -- wpp.com-sea-containers
      - name: theothers.uk.com
        run: npm run transform -- theothers.uk.com
      - name: rosettaarts.org
        run: npm run transform -- rosettaarts.org
      - name: westminster.gov.uk-maida-vale-library
        run: npm run transform -- westminster.gov.uk-maida-vale-library
      - name: instagram.com-casalavandauk
        run: npm run transform -- instagram.com-casalavandauk
      - name: crossroadswomen.net
        run: npm run transform -- crossroadswomen.net
      - name: parksideca.org.uk
        run: npm run transform -- parksideca.org.uk
      - name: agakhancentre.org.uk
        run: npm run transform -- agakhancentre.org.uk
      - name: stbarnabas-southfields.org.uk
        run: npm run transform -- stbarnabas-southfields.org.uk
      - name: kanaloa.org
        run: npm run transform -- kanaloa.org
      - name: goodenough.ac.uk
        run: npm run transform -- goodenough.ac.uk
      - name: angelcomedy.co.uk-bill-murray
        run: npm run transform -- angelcomedy.co.uk-bill-murray
      - name: royalgreenwich.gov.uk-eltham-park-south
        run: npm run transform -- royalgreenwich.gov.uk-eltham-park-south
      - name: theblackeel.uk
        run: npm run transform -- theblackeel.uk
      - name: dehemspub.co.uk
        run: npm run transform -- dehemspub.co.uk
      - name: jaguarshoes.com-the-victoria
        run: npm run transform -- jaguarshoes.com-the-victoria
      - name: thewinchesterhighgate.co.uk
        run: npm run transform -- thewinchesterhighgate.co.uk
      - name: reference-point.uk
        run: npm run transform -- reference-point.uk
      - name: centre151.com
        run: npm run transform -- centre151.com
      - name: antwerparms.co.uk
        run: npm run transform -- antwerparms.co.uk
      - name: spanners.club
        run: npm run transform -- spanners.club
      - name: shapeslewisham.co.uk
        run: npm run transform -- shapeslewisham.co.uk
      - name: lacamionera.com
        run: npm run transform -- lacamionera.com
      - name: lordshiphub.org
        run: npm run transform -- lordshiphub.org
      - name: theshowroom.org
        run: npm run transform -- theshowroom.org
      - name: eseacommunitycentre.org.uk
        run: npm run transform -- eseacommunitycentre.org.uk
      - name: maydayrooms.org
        run: npm run transform -- maydayrooms.org
      - name: stmaryswalthamstow.org
        run: npm run transform -- stmaryswalthamstow.org
      - name: londres.cervantes.es
        run: npm run transform -- londres.cervantes.es

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: transform_external_events_7
          path: transformed-data/

  # ------------------------------------------------------------------------------
  # Transform all cinemas not part of a large chain (Part 1)
  # ------------------------------------------------------------------------------
  transform_remaining_1:
    name: Transform Remaining 1
    needs: [download_retrieved_data, download_historical_data]
    runs-on: ubuntu-latest
    env:
      TZ: Europe/London
      MOVIEDB_API_KEY: ${{ secrets.MOVIEDB_API_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      PAT: ${{ secrets.PAT }}
    steps:
      - uses: clusterflick/.github/setup@main
      - name: Set cache date
        run: echo "CACHE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Cache LLM responses
        uses: actions/cache@v5
        with:
          path: cache-llm
          key: cache-llm-${{ github.job }}-${{ env.CACHE_DATE }}
      - name: Download Retrieved Data
        uses: actions/download-artifact@v8
        with:
          name: retrieved-data
          path: retrieved-data/
          github-token: ${{ github.token }}
      - name: Download Historical Data
        uses: actions/download-artifact@v8
        with:
          name: combined-data
          path: combined-data/
          github-token: ${{ github.token }}

      - name: olympiccinema.com
        run: npm run transform -- olympiccinema.com
      - name: thecinemaatselfridges.com
        run: npm run transform -- thecinemaatselfridges.com
      - name: thecinemainthepowerstation.com
        run: npm run transform -- thecinemainthepowerstation.com
      - name: regentstreetcinema.com
        run: npm run transform -- regentstreetcinema.com
      - name: phoenixcinema.co.uk
        run: npm run transform -- phoenixcinema.co.uk
      - name: actonecinema.co.uk
        run: npm run transform -- actonecinema.co.uk
      - name: chiswickcinema.co.uk
        run: npm run transform -- chiswickcinema.co.uk
      - name: riocinema.org.uk
        run: npm run transform -- riocinema.org.uk
      - name: thelexicinema.co.uk
        run: npm run transform -- thelexicinema.co.uk
      - name: thearzner.com
        run: npm run transform -- thearzner.com

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: transform_remaining_1
          path: transformed-data/

  # ------------------------------------------------------------------------------
  # Transform all cinemas not part of a large chain (Part 2)
  # ------------------------------------------------------------------------------
  transform_remaining_2:
    name: Transform Remaining 2
    needs: [download_retrieved_data, download_historical_data]
    runs-on: ubuntu-latest
    env:
      TZ: Europe/London
      MOVIEDB_API_KEY: ${{ secrets.MOVIEDB_API_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      PAT: ${{ secrets.PAT }}
    steps:
      - uses: clusterflick/.github/setup@main
      - name: Set cache date
        run: echo "CACHE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Cache LLM responses
        uses: actions/cache@v5
        with:
          path: cache-llm
          key: cache-llm-${{ github.job }}-${{ env.CACHE_DATE }}
      - name: Download Retrieved Data
        uses: actions/download-artifact@v8
        with:
          name: retrieved-data
          path: retrieved-data/
          github-token: ${{ github.token }}
      - name: Download Historical Data
        uses: actions/download-artifact@v8
        with:
          name: combined-data
          path: combined-data/
          github-token: ${{ github.token }}

      - name: lumiereromford.com
        run: npm run transform -- lumiereromford.com
      - name: metrocinema.co.uk
        run: npm run transform -- metrocinema.co.uk
      - name: backyardcinema.co.uk
        run: npm run transform -- backyardcinema.co.uk
      - name: eventimapollo.com
        run: npm run transform -- eventimapollo.com
      - name: thenickel.co.uk
        run: npm run transform -- thenickel.co.uk
      - name: thegardencinema.co.uk
        run: npm run transform -- thegardencinema.co.uk
      - name: richmix.org.uk
        run: npm run transform -- richmix.org.uk
      - name: closeupfilmcentre.com
        run: npm run transform -- closeupfilmcentre.com
      - name: forestcinema.co.uk
        run: npm run transform -- forestcinema.co.uk
      - name: bushtheatre.co.uk
        run: npm run transform -- bushtheatre.co.uk

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: transform_remaining_2
          path: transformed-data/

  # ------------------------------------------------------------------------------
  # Transform all cinemas not part of a large chain (Part 3)
  # ------------------------------------------------------------------------------
  transform_remaining_3:
    name: Transform Remaining 3
    needs: [download_retrieved_data, download_historical_data]
    runs-on: ubuntu-latest
    env:
      TZ: Europe/London
      MOVIEDB_API_KEY: ${{ secrets.MOVIEDB_API_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      PAT: ${{ secrets.PAT }}
    steps:
      - uses: clusterflick/.github/setup@main
      - name: Set cache date
        run: echo "CACHE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Cache LLM responses
        uses: actions/cache@v5
        with:
          path: cache-llm
          key: cache-llm-${{ github.job }}-${{ env.CACHE_DATE }}
      - name: Download Retrieved Data
        uses: actions/download-artifact@v8
        with:
          name: retrieved-data
          path: retrieved-data/
          github-token: ${{ github.token }}
      - name: Download Historical Data
        uses: actions/download-artifact@v8
        with:
          name: combined-data
          path: combined-data/
          github-token: ${{ github.token }}

      - name: arthousecrouchend.co.uk
        run: npm run transform -- arthousecrouchend.co.uk
      - name: thecastlecinema.com
        run: npm run transform -- thecastlecinema.com
      - name: castlesidcup.com
        run: npm run transform -- castlesidcup.com
      - name: davidleancinema.org.uk
        run: npm run transform -- davidleancinema.org.uk
      - name: kilntheatre.com
        run: npm run transform -- kilntheatre.com
      - name: sandsfilms.co.uk
        run: npm run transform -- sandsfilms.co.uk
      - name: coldharbourblue.com
        run: npm run transform -- coldharbourblue.com
      - name: goodshepherdstudios.com
        run: npm run transform -- goodshepherdstudios.com
      - name: thebathhouse.co
        run: npm run transform -- thebathhouse.co
      - name: adventurecinema.co.uk-kew-gardens
        run: npm run transform -- adventurecinema.co.uk-kew-gardens
      - name: canarywharf.com-summer-screens
        run: npm run transform -- canarywharf.com-summer-screens
      - name: stanleyarts.org
        run: npm run transform -- stanleyarts.org

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: transform_remaining_3
          path: transformed-data/

  # ------------------------------------------------------------------------------
  # Transform all cinemas not part of a large chain (Part 4)
  # ------------------------------------------------------------------------------
  transform_remaining_4:
    name: Transform Remaining 4
    needs: [download_retrieved_data, download_historical_data]
    runs-on: ubuntu-latest
    env:
      TZ: Europe/London
      MOVIEDB_API_KEY: ${{ secrets.MOVIEDB_API_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      PAT: ${{ secrets.PAT }}
    steps:
      - uses: clusterflick/.github/setup@main
      - name: Set cache date
        run: echo "CACHE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Cache LLM responses
        uses: actions/cache@v5
        with:
          path: cache-llm
          key: cache-llm-${{ github.job }}-${{ env.CACHE_DATE }}
      - name: Download Retrieved Data
        uses: actions/download-artifact@v8
        with:
          name: retrieved-data
          path: retrieved-data/
          github-token: ${{ github.token }}
      - name: Download Historical Data
        uses: actions/download-artifact@v8
        with:
          name: combined-data
          path: combined-data/
          github-token: ${{ github.token }}

      - name: siobhandavies.com
        run: npm run transform -- siobhandavies.com
      - name: thelondonarchives.org
        run: npm run transform -- thelondonarchives.org
      - name: peckhamplex.london
        run: npm run transform -- peckhamplex.london
      - name: royalalberthall.com
        run: npm run transform -- royalalberthall.com
      - name: omniplex.co.uk-sutton
        run: npm run transform -- omniplex.co.uk-sutton
      - name: fulhampier.com
        run: npm run transform -- fulhampier.com
      - name: acflondon.org
        run: npm run transform -- acflondon.org
      - name: thehorsehospital.com
        run: npm run transform -- thehorsehospital.com
      - name: thehammondtheatre.co.uk
        run: npm run transform -- thehammondtheatre.co.uk
      - name: lewisham.gov.uk-deptford-lounge
        run: npm run transform -- lewisham.gov.uk-deptford-lounge
      - name: bbk.ac.uk-central
        run: npm run transform -- bbk.ac.uk-central
      - name: bbk.ac.uk-cinema
        run: npm run transform -- bbk.ac.uk-cinema
      - name: dugdaleartscentre.co.uk
        run: npm run transform -- dugdaleartscentre.co.uk
      - name: sydenhamarts.co.uk
        run: npm run transform -- sydenhamarts.co.uk
      - name: whitechapelgallery.org
        run: npm run transform -- whitechapelgallery.org
      - name: not-nowhere.org
        run: npm run transform -- not-nowhere.org
      - name: museumofthehome.org.uk
        run: npm run transform -- museumofthehome.org.uk
      - name: wiltons.org.uk
        run: npm run transform -- wiltons.org.uk
      - name: cadoganhall.com
        run: npm run transform -- cadoganhall.com
      - name: royalparks.org.uk-hyde-park
        run: npm run transform -- royalparks.org.uk-hyde-park
      - name: londonbridgecity.co.uk
        run: npm run transform -- londonbridgecity.co.uk
      - name: rafmuseum.org.uk-london
        run: npm run transform -- rafmuseum.org.uk-london
      - name: lbhf.gov.uk-lyric-square
        run: npm run transform -- lbhf.gov.uk-lyric-square

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: transform_remaining_4
          path: transformed-data/

  # ------------------------------------------------------------------------------
  # Create release using data from all jobs
  # ------------------------------------------------------------------------------
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    # ncipollo/release-action creates a release + tag via GITHUB_TOKEN,
    # which requires contents: write (top-level default is contents: read).
    # A job-level block replaces the top-level one, so actions: read is
    # repeated here for download-artifact.
    permissions:
      contents: write
      actions: read
    needs:
      [
        transform_bfi,
        transform_cineworld,
        transform_curzon,
        transform_electric_cinema,
        transform_rooftopcinemaclub,
        transform_tate,
        transform_firmdale_hotels,
        transform_everyman,
        transform_vue,
        transform_odeon,
        transform_picturehouses,
        transform_organisations_1,
        transform_organisations_2,
        transform_external_events_1,
        transform_external_events_2,
        transform_external_events_3,
        transform_external_events_4,
        transform_external_events_5,
        transform_external_events_6,
        transform_external_events_7,
        transform_remaining_1,
        transform_remaining_2,
        transform_remaining_3,
        transform_remaining_4,
      ]
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v8
        with:
          path: transformed-data/
          pattern: transform_*
          merge-multiple: true
          github-token: ${{ github.token }}
      - name: Generate Tag
        run: echo "TAG=$(TZ=Europe/London date +'%Y%m%d.%H%M%S')" >> $GITHUB_ENV
      - uses: ncipollo/release-action@v1
        id: release
        with:
          allowUpdates: false
          artifactErrorsFailBuild: true
          artifacts: "transformed-data/*"
          makeLatest: true
          tag: ${{ env.TAG }}
          commit: main
          body: |
            Created by job ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      - name: Output summary
        run: |
          echo "🔖 New release - ${{ steps.release.outputs.html_url }}" >> $GITHUB_STEP_SUMMARY

      - name: Repository Dispatch for data-cached
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.PAT }}
          repository: clusterflick/data-cached
          event-type: release_event

      - name: Repository Dispatch for data-calendar
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.PAT }}
          repository: clusterflick/data-calendar
          event-type: release_event

      - name: Repository Dispatch for data-analysed
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.PAT }}
          repository: clusterflick/data-analysed
          event-type: compare_releases

      - name: Repository Dispatch for scripts
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.PAT }}
          repository: clusterflick/scripts
          event-type: release_event
